version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: detailed
deploy:
- provider: NuGet
  api_key:
    secure: RlnvQ0Puvb5Sx3twkRWSXdZbQzZExnuPACZQrmFDXUaxkJwcCOv3VZAvI3UlyuFr
  skip_symbols: false
  on:
    branch: master